version: "3.8"
services:
  app:
    image: eq_rng:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      RUST_LOG: info
    command: ["eq_rng"]
