version: "3.8"
services:
  app:
    container_name: eqrng_app
    image: eq_rng:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      RUST_LOG: info
      EQ_RNG_ENV: production
      RATING_IP_HASH_KEY: "change-this-to-a-secure-random-32plus-character-string-for-production"
      ALLOWED_ORIGINS: "https://eqrng.com"
    volumes:
      - ./data:/opt/eq_rng/data
