version: "3.8"
services:
  app:
    image: eqrng:latest
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "8000:8080"
    environment:
      RUST_LOG: info
