version: "3.8"
services:
  app:
    image: eq_rng:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      RUST_LOG: debug
      EQ_RNG_ENV: development
      RATING_IP_HASH_KEY: "development-key-change-for-production-use-32plus-chars"
    volumes:
      - ./data:/opt/eq_rng/data
